name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    fail-fast: true
    runs-on: ${{ matrix.env }}
    matrix:
      env: [macos-10.15, windows-2019]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install and Build
        run: |
          npm install
          npm run-script test
